### 경영데이터마이닝 Term Project

1. Data
- KPMG Customer Demography Cleaned Dataset

2. Business Problem
- 자전거 및 자전거 관련 물품을 판매하는 “Sprocket”사의 고객들을 특성에 맞는 고객군으로 분류한 후 타겟 마케팅 실시

3. Data Mining
- "Sprocket"사의 기존 고객들을 데이터에 기반하여 customer segmentation 실시

4. Method
- 비지도학습 기반의 k-means clustering

In [203]:
# 필요한 library import

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

In [117]:
# data load

df = pd.read_csv('/Users/ldw/Documents/경영데이터마이닝/term_project/KPMG_Customer_Demography.csv') 
df

customer_id      First_Name  Last_Name  gender         DOB  AGE  \
0               1         Laraine  Medendorp  Female  10/12/1953   69   
1               2             Eli    Bockman    Male  12/16/1980   42   
2               4          Talbot        NaN    Male   10/3/1961   61   
3               5  Sheila-kathryn     Calton  Female   5/13/1977   45   
4               6            Curr  Duckhouse    Male   9/16/1966   56   
...           ...             ...        ...     ...         ...  ...   
3903         3995           Rusty     Iapico    Male  12/12/1975   47   
3904         3996         Rosalia   Halgarth  Female    8/9/1975   47   
3905         3997          Blanch     Nisuis  Female   7/13/2001   21   
3906         3999       Patrizius        NaN    Male  10/24/1973   49   
3907         4000           Kippy    Oldland    Male   11/5/1991   31   

      past_3_years_bike_related_purchases job_industry_category  \
0                                      93                Health   
1                                      81    Financial Services   
2                                      33                    IT   
3                                      56                   NaN   
4                                      35                Retail   
...                                   ...                   ...   
3903                                   93         Manufacturing   
3904                                    8                Health   
3905                                   87         Manufacturing   
3906                                   11         Manufacturing   
3907                                   76                   NaN   

         wealth_segment deceased_indicator  tenure Owns_Car  \
0         Mass Customer                  N      11      Yes   
1         Mass Customer                  N      16      Yes   
2         Mass Customer                  N       7       No   
3     Affluent Customer                  N       8      Yes   
4        High Net Worth                  N      13      Yes   
...                 ...                ...     ...      ...   
3903      Mass Customer                  N      14      Yes   
3904      Mass Customer                  N      19       No   
3905     High Net Worth                  N       1      Yes   
3906  Affluent Customer                  N      10      Yes   
3907  Affluent Customer                  N      11       No   

                        Address  Postcode            State    Country  \
0            060 Morning Avenue      2016  New South Wales  Australia   
1           6 Meadow Vale Court      2153  New South Wales  Australia   
2            0 Holy Cross Court      4211       Queensland  Australia   
3           17979 Del Mar Point      2448  New South Wales  Australia   
4              9 Oakridge Court      3216         Victoria  Australia   
...                         ...       ...              ...        ...   
3903              613 Erie Lane      2088  New South Wales  Australia   
3904         0 Transport Center      3977         Victoria  Australia   
3905        4 Dovetail Crossing      2350  New South Wales  Australia   
3906            1482 Hauk Trail      3064         Victoria  Australia   
3907  57042 Village Green Point      4511       Queensland  Australia   

      property_valuation  
0                     10  
1                     10  
2                      9  
3                      4  
4                      9  
...                  ...  
3903                  12  
3904                   6  
3905                   2  
3906                   3  
3907                   6  

[3908 rows x 17 columns]

In [118]:
# index를 재설정

df.index = range(1, 3909)
df

customer_id      First_Name  Last_Name  gender         DOB  AGE  \
1               1         Laraine  Medendorp  Female  10/12/1953   69   
2               2             Eli    Bockman    Male  12/16/1980   42   
3               4          Talbot        NaN    Male   10/3/1961   61   
4               5  Sheila-kathryn     Calton  Female   5/13/1977   45   
5               6            Curr  Duckhouse    Male   9/16/1966   56   
...           ...             ...        ...     ...         ...  ...   
3904         3995           Rusty     Iapico    Male  12/12/1975   47   
3905         3996         Rosalia   Halgarth  Female    8/9/1975   47   
3906         3997          Blanch     Nisuis  Female   7/13/2001   21   
3907         3999       Patrizius        NaN    Male  10/24/1973   49   
3908         4000           Kippy    Oldland    Male   11/5/1991   31   

      past_3_years_bike_related_purchases job_industry_category  \
1                                      93                Health   
2                                      81    Financial Services   
3                                      33                    IT   
4                                      56                   NaN   
5                                      35                Retail   
...                                   ...                   ...   
3904                                   93         Manufacturing   
3905                                    8                Health   
3906                                   87         Manufacturing   
3907                                   11         Manufacturing   
3908                                   76                   NaN   

         wealth_segment deceased_indicator  tenure Owns_Car  \
1         Mass Customer                  N      11      Yes   
2         Mass Customer                  N      16      Yes   
3         Mass Customer                  N       7       No   
4     Affluent Customer                  N       8      Yes   
5        High Net Worth                  N      13      Yes   
...                 ...                ...     ...      ...   
3904      Mass Customer                  N      14      Yes   
3905      Mass Customer                  N      19       No   
3906     High Net Worth                  N       1      Yes   
3907  Affluent Customer                  N      10      Yes   
3908  Affluent Customer                  N      11       No   

                        Address  Postcode            State    Country  \
1            060 Morning Avenue      2016  New South Wales  Australia   
2           6 Meadow Vale Court      2153  New South Wales  Australia   
3            0 Holy Cross Court      4211       Queensland  Australia   
4           17979 Del Mar Point      2448  New South Wales  Australia   
5              9 Oakridge Court      3216         Victoria  Australia   
...                         ...       ...              ...        ...   
3904              613 Erie Lane      2088  New South Wales  Australia   
3905         0 Transport Center      3977         Victoria  Australia   
3906        4 Dovetail Crossing      2350  New South Wales  Australia   
3907            1482 Hauk Trail      3064         Victoria  Australia   
3908  57042 Village Green Point      4511       Queensland  Australia   

      property_valuation  
1                     10  
2                     10  
3                      9  
4                      4  
5                      9  
...                  ...  
3904                  12  
3905                   6  
3906                   2  
3907                   3  
3908                   6  

[3908 rows x 17 columns]

In [119]:
# 불필요한 column 삭제

df.drop(columns=['customer_id', 'First_Name', 'Last_Name', 'DOB', 'deceased_indicator', 'tenure', 'Address', 'Postcode', 'Country', 'property_valuation'], axis=0, inplace=True)
df

gender  AGE  past_3_years_bike_related_purchases job_industry_category  \
1     Female   69                                   93                Health   
2       Male   42                                   81    Financial Services   
3       Male   61                                   33                    IT   
4     Female   45                                   56                   NaN   
5       Male   56                                   35                Retail   
...      ...  ...                                  ...                   ...   
3904    Male   47                                   93         Manufacturing   
3905  Female   47                                    8                Health   
3906  Female   21                                   87         Manufacturing   
3907    Male   49                                   11         Manufacturing   
3908    Male   31                                   76                   NaN   

         wealth_segment Owns_Car            State  
1         Mass Customer      Yes  New South Wales  
2         Mass Customer      Yes  New South Wales  
3         Mass Customer       No       Queensland  
4     Affluent Customer      Yes  New South Wales  
5        High Net Worth      Yes         Victoria  
...                 ...      ...              ...  
3904      Mass Customer      Yes  New South Wales  
3905      Mass Customer       No         Victoria  
3906     High Net Worth      Yes  New South Wales  
3907  Affluent Customer      Yes         Victoria  
3908  Affluent Customer       No       Queensland  

[3908 rows x 7 columns]

In [120]:
# 각 feature의 null 값 확인 

df.isnull().sum()

gender                                   0
AGE                                      0
past_3_years_bike_related_purchases      0
job_industry_category                  655
wealth_segment                           0
Owns_Car                                 0
State                                    0
dtype: int64

In [121]:
# null값이 655개인 job_industry_category column 삭제

df.drop(columns='job_industry_category', axis=0, inplace=True)
df

gender  AGE  past_3_years_bike_related_purchases     wealth_segment  \
1     Female   69                                   93      Mass Customer   
2       Male   42                                   81      Mass Customer   
3       Male   61                                   33      Mass Customer   
4     Female   45                                   56  Affluent Customer   
5       Male   56                                   35     High Net Worth   
...      ...  ...                                  ...                ...   
3904    Male   47                                   93      Mass Customer   
3905  Female   47                                    8      Mass Customer   
3906  Female   21                                   87     High Net Worth   
3907    Male   49                                   11  Affluent Customer   
3908    Male   31                                   76  Affluent Customer   

     Owns_Car            State  
1         Yes  New South Wales  
2         Yes  New South Wales  
3          No       Queensland  
4         Yes  New South Wales  
5         Yes         Victoria  
...       ...              ...  
3904      Yes  New South Wales  
3905       No         Victoria  
3906      Yes  New South Wales  
3907      Yes         Victoria  
3908       No       Queensland  

[3908 rows x 6 columns]

In [122]:
# 범주형 데이터를 수치형 데이터로 one-hot encoding

ohe = OneHotEncoder(sparse=False)
encoded_features = ohe.fit_transform(np.array(df[['gender', 'wealth_segment', 'Owns_Car', 'State']]))
encoded_features

array([[1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 1., ..., 0., 0., 1.],
       [0., 1., 1., ..., 0., 1., 0.]])

In [123]:
encoded_features.shape

(3908, 10)

In [124]:
# one-hot encoding된 column 삭제

df.drop(columns=['gender', 'wealth_segment', 'Owns_Car', 'State'], axis=0, inplace=True)
df

AGE  past_3_years_bike_related_purchases
1      69                                   93
2      42                                   81
3      61                                   33
4      45                                   56
5      56                                   35
...   ...                                  ...
3904   47                                   93
3905   47                                    8
3906   21                                   87
3907   49                                   11
3908   31                                   76

[3908 rows x 2 columns]

In [282]:
# 수치형 feature를 0 ~ 1의 범위로 정규화

scaler = MinMaxScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df), columns=['AGE', 'past_3_years_bike_related_purchases'])
df_scaled

# df_scaled[:, 'past_3_years_bike_related_purchases'] = df_scaled[:, 'past_3_years_bike_related_purchases'] + 10 
# -> 가중치 부여

AGE  past_3_years_bike_related_purchases
0     0.690141                             0.939394
1     0.309859                             0.818182
2     0.577465                             0.333333
3     0.352113                             0.565657
4     0.507042                             0.353535
...        ...                                  ...
3903  0.380282                             0.939394
3904  0.380282                             0.080808
3905  0.014085                             0.878788
3906  0.408451                             0.111111
3907  0.154930                             0.767677

[3908 rows x 2 columns]

In [284]:
# one-hot encoding으로 수치화시킨 feature와 기존의 수치형 feature를 포함한 전체 feature 데이터 생성

features = np.hstack((df_scaled, np.array(encoded_features)))
features

array([[0.69014085, 0.93939394, 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.30985915, 0.81818182, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.57746479, 0.33333333, 0.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.01408451, 0.87878788, 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.4084507 , 0.11111111, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.15492958, 0.76767677, 0.        , ..., 0.        , 1.        ,
        0.        ]])

In [285]:
# 12차원의 feature를 2차원으로 차원 축소 (PCA)

pca = PCA(n_components=2)
features_pca = pca.fit_transform(features)
features_pca

array([[ 0.1473412 , -1.00107735],
       [ 0.93769407,  0.16269447],
       [-0.25377708,  1.03171401],
       ...,
       [ 0.27704108, -0.97457246],
       [ 1.03310509,  0.27622447],
       [-0.10217247,  1.07656083]])

In [286]:
# 군집 타당성 지표 중 하나인 실루엣 지표를 통해 최적의 군집 개수 결정
score_ls = []
for i in range(2, 10): 
    kmeans = KMeans(n_clusters=i)
    kmeans.fit(features_pca)
    cluster = kmeans.predict(features_pca)
    score = silhouette_score(features_pca, cluster)
    score_ls.append(score)
    print("n_cluster=%d 일 때의 실루엣 지표: %.10f" % (i, score))

n_cluster=2 일 때의 실루엣 지표: 0.5541779180
n_cluster=3 일 때의 실루엣 지표: 0.7030300833
n_cluster=4 일 때의 실루엣 지표: 0.9225075407
n_cluster=5 일 때의 실루엣 지표: 0.8513327669
n_cluster=6 일 때의 실루엣 지표: 0.7813346874
n_cluster=7 일 때의 실루엣 지표: 0.7156339439
n_cluster=8 일 때의 실루엣 지표: 0.6509682073
n_cluster=9 일 때의 실루엣 지표: 0.6780053309


In [287]:
# 각 군집 개수에 대한 실루엣 지표 시각화

plt.figure(figsize=(7,5))
plt.plot(range(2, 10), score_ls, '-o')
plt.xlabel('number of cluster')
plt.ylabel('silhouette score')
plt.show

<function matplotlib.pyplot.show(close=None, block=None)>

In [288]:
# 4개의 군집으로 k_means 군집화

kmeans = KMeans(n_clusters=4)
kmeans.fit(features_pca)
cluster = kmeans.predict(features_pca)
cluster

array([3, 0, 2, ..., 3, 0, 2], dtype=int32)

In [290]:
# 4개의 군집으로 군집화 했을 경우의 실루엣 지표

score = silhouette_score(features_pca, cluster)
print("최적의 군집 개수에 대한 실루엣 지표: ", score)

최적의 군집 개수에 대한 실루엣 지표:  0.9225075407270745


In [293]:
# 2차원으로 차원 축소된 feature와 군집 결과인 cluster를 column으로 갖는 dataframe 생성

df_pca = pd.DataFrame(features_pca, columns=['pca_x', 'pca_y'])
df_pca['cluster'] = cluster
df_pca

pca_x     pca_y  cluster
0     0.147341 -1.001077        3
1     0.937694  0.162694        0
2    -0.253777  1.031714        2
3     0.297081 -0.968333        3
4     1.013013  0.267847        0
...        ...       ...      ...
3903  0.937995  0.164301        0
3904 -1.068207 -0.130962        1
3905  0.277041 -0.974572        3
3906  1.033105  0.276224        0
3907 -0.102172  1.076561        2

[3908 rows x 3 columns]

In [296]:
# kmeans 군집화 결과 시각화

# 각 cluster 값인 경우마다 Index 추출
marker0_ind = df_pca[df_pca['cluster']==0].index
marker1_ind = df_pca[df_pca['cluster']==1].index
marker2_ind = df_pca[df_pca['cluster']==2].index
marker3_ind = df_pca[df_pca['cluster']==3].index

# 각 cluster에 해당하는 Index로 pca_x, pca_y 값 추출
plt.scatter(x=df_pca.loc[marker0_ind,'pca_x'], y=df_pca.loc[marker0_ind,'pca_y'], marker='o') 
plt.scatter(x=df_pca.loc[marker1_ind,'pca_x'], y=df_pca.loc[marker1_ind,'pca_y'], marker='^') 
plt.scatter(x=df_pca.loc[marker2_ind,'pca_x'], y=df_pca.loc[marker2_ind,'pca_y'], marker='<') 
plt.scatter(x=df_pca.loc[marker3_ind,'pca_x'], y=df_pca.loc[marker3_ind,'pca_y'], marker='>') 

plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.title('4 Clusters Visualization by 2 PCA Components')
plt.show()